version: 0.2

phases:
  install:
  
    runtime-versions:
      docker: 18
      
    commands:
      - npm install -g @angular/cli
      - npm install
      
  build:
    commands:
      - ng build --prod --aot false --build-optimizer=false

  post_build:
    commands:
      - aws s3 sync ./dist/testAWSGitCICD s3://cicdangulartest --acl 'public-read' --delete
      
