version: 0.2

phases:
  install:
  
  runtime-versions:
      docker: 18
      
    commands:
      - echo Installing Angular
      - npm install -g @angular/cli
      - echo Install
      - npm install
      - echo build
      - ng build
  build:
    commands:
      - ng build
  post_build:
    commands:
      - echo Build completed
      
artifacts:
  files:
    - '**/*'
