version: 0.2

phases:
  install:
  
    runtime-versions:
      docker: 18
      
    commands:
      - npm install -g @angular/cli
      - npm install
      - npm install -g protractor
      - webdriver-manager update
      
      
  build:
    commands:
      - ng build --prod --aot false --build-optimizer=false
      #- webdriver-manager start
      #- protractor conf.js
  post_build:
    commands:
      - echo Build completed
      
artifacts:
  files:
    - dist/testAWSGitCICD/
